### ISSUE TITLE
User story #6 - Distance to interest calculator

### ISSUE THREAD

**Issue by DominiqueProulx** [Broke-Brokers/Broke_BRokers-soen341projectF2023#16]

**Comment by DominiqueProulx** [comment]
from : #24 
### FOR SPRINT 4
## MORTAGE CALCULATOR

As a Homebuyer , I want to have a distance to interest calculator on the property page so that I can calculate would be base don the price of the house and the interest .



## User acceptance flow 

1. Home buyer  accesses the website
2.  Homebuyer clicks on their profile.
3. In the profile the Homebuyer can do CRUD on it's 5 interests. (NameOfPerson or NameOfStore + address)
4. Home buyer  on "Search for a property" on the navigation bar6. The home buyer accesses a property page through the results of the search for property page7.  At the bottom of the page there is a a list of the homebuyer's interest at the distance this house is to those interests
8. Homebuyer/Renter is allowed 5 interests 
9.  TBC



HIERARCHY 
``` 
     Main page + login  
           Search for Properties
                 property page
                   => Distance to interest calculator
           Search for brokers
           Homebuyers Profile
                 Saved Favorites
           
```
## Acceptance Criteria 

-
- [ ]  Mortgage calculator appears on property page
- [ ] 
- [ ] Must match mockup
- [ ] A unit test Snapshot must be done for the component 

---

##TASK BREAKDOWN

- [ ] TASK - 1.6.1 Mockup for CRUD on interest
- [ ]  TASK - 1.6.2  Homebuyer's interest database created
- [ ] TASK -  1.6.3 CRUD on interest list.
- [ ]  TASK - 1.6.4 Profile CRUD on interest section
