### ISSUE TITLE
TASK - 1.1.2

### ISSUE THREAD

**Issue by taylcr** [Broke-Brokers/Broke_BRokers-soen341projectF2023#188]
from : #124 

## TASK DESCRIPTION 

As I homebuyer or home renter, I want to have a search page with a search bar and result gallery.

## ACCEPTANCE CRITERIA

I want the search bar to contain research criteria for a house:
- [ ] Search by city
- [ ] Search by neighborhood
- [ ] House for sale
- [ ] House for rent
- [ ] Price range
- [ ] Number of bedrooms
- [ ] Number of bathrooms
- [ ] Caracteristic such as Pool, waterfront, garage, elevator, fireplace
