### ISSUE TITLE
TASK - Create two acceptance tests for 1.4, 3.1 and 3.5

### ISSUE THREAD

**Issue by DominiqueProulx** [Broke-Brokers/Broke_BRokers-soen341projectF2023#221]
from : #131 #143 #142  

## TASK DESCRIPTION 

As a development team, I want to write acceptance tests so that I can test the implementation of my features .

## ACCEPTANCE CRITERIA

- [ ] 2 AT written for 1.4
- [ ] 2 AT written for 3.1
- [ ] 2 AT written for 3.5

**Comment by DominiqueProulx** [comment]
This is  a double from #208  create by mistake
