### ISSUE TITLE
User Story #1 - Homebuyers Implemented

### ISSUE THREAD

**Issue by DominiqueProulx** [Broke-Brokers/Broke_BRokers-soen341projectF2023#24]

**Comment by DominiqueProulx** [comment]
### FOR SPRINT2

HIERARCHY 
``` 
     Main page + login  
           Search for Proerties
           Homebuyers Profile
                 Saved Favorites
           Search for brokers
           Mortage Calculator 
```
### Property Search page   (issue created) 

- [x] Property search from main navigaiton menu
- [x] Property Search page:[SEARCH BAR]At the top.Bar with search criteria(location,city, neighborhood, ZIP code, price range, number of bedrooms, and amenities.) #60 
- [x] Property Search page: [FILTER] At the top. List of common amenities or features that I can select or deselect to filter the properties.( options such as swimming pool, garage, garden, etc.) #60 
- [x] Property Search page: [BUTTON] Request Visit
- [x] Property Search page: [FORM](on request visit click) : open a form or dialog where I can provide the following information and submit them after:
* My preferred date and time for the viewing appointment.
* Contact information, including the name, email address, and phone number
- [ ] Property Search page: [FORM](on request form submit):  Confirmation message indicating that the request has been received by the system.
- [ ] Property Search page: [FORM](on request form submit):  Email confirmation to the email address provided, summarizing the details of the viewing request and receipt.
- [ ] Property Search page: [BUTTON] Button "save" when viewing a property.
- [ ]  Property Search page: (on save button click) : property saved to homebuyers Save list #49  #60 
 
### property page ### 

- [ ] link back to search result
- [ ] image of house exterior#60 #25 
- [ ] image of house interior#60 #25 
- [ ] Info : price #60 #25 
- [ ] Adress #60 #25 
- [ ] Construction year #60 #25 
- [ ] rectangle with broker related to the house and contact info #34 #63 #25 
- [ ] [BUTTON] Request a visit #72
- [ ] [BUTTON] Save to favorites #71 #25 


**Homebuyer User profile** 

- [ ] Homebuyer User profile : The user can view the list of saved favorite properties from his user profile 
- [ ] Homebuyer User profile : Display of Homebuyer information
- [ ] Homebuyer User profile :  Edit Homebuyer information
- [ ]  Homebuyer User profile : [BUTTON]An option to remove properties from my saved favorites. #67 



** And then then ** :
- [ ]  Fire up Test #28 
- [ ]Fire up  Refactoring #31 


---

**Comment by DominiqueProulx** [comment]
24.1 Property Search page 

- [ ] Property search from main navigaiton menu
- [ ] Property Search page:[SEARCH BAR]At the top.Bar with search criteria(location,city, neighborhood, ZIP code, price range, number of bedrooms, and amenities.) #60 
- [ ] Property Search page: [FILTER] At the top. List of common amenities or features that I can select or deselect to filter the properties.( options such as swimming pool, garage, garden, etc.) #60 
- [ ] Property Search page: [BUTTON] Request Visit
- [ ] Property Search page: [FORM](on request visit click) : open a form or dialog where I can provide the following information and submit them after:
* My preferred date and time for the viewing appointment.
* Contact information, including the name, email address, and phone number
- [ ] Property Search page: [FORM](on request form submit):  Confirmation message indicating that the request has been received by the system.
- [ ] Property Search page: [FORM](on request form submit):  Email confirmation to the email address provided, summarizing the details of the viewing request and receipt.
- [ ] Property Search page: [BUTTON] Button "save" when viewing a property.
- [ ]  Property Search page: (on save button click) : property saved to homebuyers Save list #49  #60

**Comment by DominiqueProulx** [comment]
### FOR SPRINT #90 **Search for Brokers**  IN SPRINT#3
- [ ] Search for brokers profile : [SEARCHBAR]A search functionality where the user can enter criteria such as location, expertise, and customer reviews to find brokers. #63 
- [ ] Search for brokers profile :  portfolio System displays a list of broker profiles that match the criteria. Broker profile should include information such as the broker's name, contact details, areas of expertise, customer reviews, and a photo. #72 
- [ ] Search for brokers profile : (on click of broker's profile) : view detailed information such as their services.
- [ ] Search for brokers profile :  [FORM] contact broker 

**Mortage calculator page** SPRINT 3

- [ ] Mortage calculator page : [FORM]The user can enter can loan amount, interest rate, loan term (in years), and property tax rate 
- [ ] Mortage calculator page : The calculator display the estimated monthly mortgage payment 


**For this task to be considered done these task must also be done : ** 
- [ ] #68 must be done
- [ ] #49 must be connected to login after #25 
- [ ] #52  must be connected to properties after #25 
- [ ] #71 this page must be completed and working
- [ ] #72 this page must be completed and working

**Comment by DominiqueProulx** [comment]
24.3 Property page

### property page ### 

- [ ] link back to search result
- [ ] image of house exterior#60 #25 
- [ ] image of house interior#60 #25 
- [ ] Info : price #60 #25 
- [ ] Adress #60 #25 
- [ ] Construction year #60 #25 
- [ ] rectangle with broker related to the house and contact info #34 #63 #25 
- [ ] [BUTTON] Request a visit #72
- [ ] [BUTTON] Save to favorites #71 #25

**Comment by DominiqueProulx** [comment]
US-1.4 Search for brokers
