### ISSUE TITLE
User Story #2  Renters  features implemented

### ISSUE THREAD

**Issue by DominiqueProulx** [Broke-Brokers/Broke_BRokers-soen341projectF2023#29]

**Comment by DominiqueProulx** [comment]
HIERARCHY 
```
     Main page + login  
           Search for Proerties
           Renters Profile
                 Saved Favorites
           Search for brokers
           
```
**Property Search page ** 
Implemented in #24 
**Renter User profile** 

- [ ] Renter User profile : The user can view the list of saved favorite properties from his user profile 
- [ ] Renter User profile : Display of Homebuyer information
- [ ] Renter User profile :  Edit Homebuyer information
- [ ]  Renter User profile : [BUTTON]An option to remove properties from my saved favorites. #67 


**Search for Brokers** 
- [ ] Search for brokers profile : [SEARCHBAR]A search functionality where the user can enter criteria such as location, expertise, and customer reviews to find brokers. #63 
- [ ] Search for brokers profile :  portfolio System displays a list of broker profiles that match the criteria. Broker profile should include information such as the broker's name, contact details, areas of expertise, customer reviews, and a photo.
- [ ] Search for brokers profile : (on click of broker's profile) : view detailed information such as their services.
- [ ] Search for brokers profile :  [FORM] contact broker 


**For this task to be considered done these task must also be done : ** 
- [ ] #68 must be done
- [ ] #49 must be connected to login after #25 
- [ ] #52  must be connected to properties after #25 
- [ ] #71 this page must be completed and working
- [ ] #72 this page must be completed and working

** And then then ** :
- [ ]  Fire up Test #28 
- [ ]Fire up  Refactoring #31 


---

**Comment by DominiqueProulx** [comment]
### For SPRINT 3

**Search for Brokers** 
- [ ] Search for brokers profile : [SEARCHBAR]A search functionality where the user can enter criteria such as location, expertise, and customer reviews to find brokers. #63 
- [ ] Search for brokers profile :  portfolio System displays a list of broker profiles that match the criteria. Broker profile should include information such as the broker's name, contact details, areas of expertise, customer reviews, and a photo.
- [ ] Search for brokers profile : (on click of broker's profile) : view detailed information such as their services.
- [ ] Search for brokers profile :  [FORM] contact broker
