### ISSUE TITLE
User Story #4 -System Admin CRUD Implemented

### ISSUE THREAD

**Issue by DominiqueProulx** [Broke-Brokers/Broke_BRokers-soen341projectF2023#37]

**Comment by isaisa002** [comment]
Resolve issue #75 
ADMNISTRATOR

USER STORY DESCRIPTION
As an administrator, I want to be able to create, read, update or delete profiles for broker

USER ACCEPTANCE FLOW

1. When login as an administrator, an alphabetic list with all the broker on the website appears
2. To create a new profile, a + button leads to a page to enter information about the broker
3. To modify or block a profile, a right click on the broke’s name appears a list allowing to modify or delete the profile



ACCEPTANCE CRITERIA
1. The list are rectangular of medium width with the broker’s picture and name as well as phone, mail and globe icon to respectively have access to it’s number, email address or message platform from the website and personal website
2. The + button is at the top left corner of the page and the edit page is as follow: the information needed at the top and a rectangular frame to enter the information below
3. A ≡ symbol at the right end of the profile allows the modify or delete icon to appear. The modify icon is a small pencil and the delete icon is a red trash bin. Selecting the modify icon leads to the page to edit the profile while selecting the trash bin allows a pop up asking if the administrator wants to really delete this profile to appear.


- [x] NEED TO DO TASK BREAKDOWN

**Comment by DominiqueProulx** [comment]
Broker card component has been created if it needs to be used  : 
BrokerCard.jsx 
 
 `import BrokerCard from '../components/property-page/BrokerCard';`
 
![image](https://github.com/Broke-Brokers/Broke_BRokers-soen341projectF2023/assets/129322102/3a9e8040-cec4-4cb9-8fcc-727812b32515)

**Comment by DominiqueProulx** [comment]
This seems to be useful for modifying the brokers information :https://www.pluralsight.com/guides/load-an-existing-database-record-to-a-react.js-form

---

#BROKERS FIELDS  from Rebecca

Table Broker {
  Broker_id integer PK
  First_Name VARCHAR
  Last_Name VARCHAR
  Phone_Number VARCHAR
  Email Varchar
  Start_date Date 
  End_date Date

**Comment by DominiqueProulx** [comment]
TASK-37.1 creating sysadmi page and routing from main page

##Task description

As a sysadmin, I need to have a profile page so that I can conduct my CRUD operations on the brokers

##Acceptance criteria

- [x] when typing /sysadminprofile we get to the sysadmin page
- [x] set up the SysAdmin.js page and write comments on what components are needed.

**Comment by DominiqueProulx** [comment]
TASK-37.2 add Button for sysadmin page 

##Task description

as a sysadmin, I want to click on a button , so that I can add a new broker

##Acceptance criteria

- [ ] Button component created
- [ ] Css created for the button
- [ ] Links to the add a broker form

**Comment by DominiqueProulx** [comment]
For the grid layout : https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/searching/

**Comment by taylcr** [comment]
creating a general profile page that will show different component depending on the type of user, the contain of the page will be dynamic contrary of having multiple profile pages for different

**Comment by taylcr** [comment]
Done, with the the react grid that will be also used for system Admin with different field, waiting for database to separate them

**Comment by isaisa002** [comment]
### For Crud with Firebase
- was able to connect Jsx with Firebase
- Implemented field and create button
- Wrote state variable that stores user input for creating and updating broker records
- Fetching Data: With a useEffect hook, was able to fetch broker data from the Firestore collection named "Broker" when the component is mounted. Those data are stored in the broker's state variable
- wrote a  createBroker function that uses the addDoc function from Firebase Firestore to add a new document to the "Broker" collection with the values provided by the user
- created modify button for each record 
- When the "button is clicked for a specific broker record, the modifyBroker function is called. This function takes the existing broker record's data (BrokerID, UserTypeID, etc.) and stores it in the corresponding state variables. It also sets the show state to true, which determines whether to show the "Create Broker" or "Update" button.
If the "Update" button is clicked, the updateBroker function is called. This function uses the updateDoc function to update an existing document in the "Broker" collection with the new values from the state variables.

**Comment by isaisa002** [comment]
Progress as for 2023-11-07:

## Update function can't work 

## Expected output 
- [x] Modify button is in card
- [x] when modify button is clicked, the update button appears 
- [ ] A modifyBroker function saves the information about the broker card where the modify button was clicked 
- [ ] The user input fields are set to the information saved by the modifyBroker function 
- [ ] User changes the information
- [ ] User clicked on updated
- [ ] Information in Firebase & broker card are changed 

## Comments 
- ModifyBroker function is in another file (Admin_Brokers_Grid.jsx) & I want to call it in a broker card
- Broker card contains the information about ONE broker 
- I want to pass the variables from broker card in the modifyBroker function
- Getting error because 
Admin_Brokers_Grid isn't well referenced in broker card
