### ISSUE TITLE
46.5 Properties visual mockup #24 #10 #11

### ISSUE THREAD

**Issue by DominiqueProulx** [Broke-Brokers/Broke_BRokers-soen341projectF2023#56]
Properties visual mockup #24 #10 #11

_Originally posted by @DominiqueProulx in https://github.com/Broke-Brokers/Broke_BRokers-soen341projectF2023/issues/46#issuecomment-1741813278_

**Comment by isaisa002** [comment]
This task is related to #24, #46 
Updated mockup for home post page when you click on a home publication in search page: https://share.goodnotes.com/s/umHDEfCzU5jKA2j4qmA1Sq

**Comment by DominiqueProulx** [comment]
@isaisa002  Let 's say I have my search with filters , it is showing 8 properties that are a match . 
- each property has a thumbnail with : image, price , adress, number of bedrooms,number of bathrooms
- I click on a property thumbnail and It opens a page with the property detailed info? 

Is that right ? Thanks!

**Comment by isaisa002** [comment]
This question was answered during the meeting of 2023-10-10

**Comment by isaisa002** [comment]
@DominiqueProulx 
In the search page, the visual for the properties is 
![image](https://github.com/Broke-Brokers/Broke_BRokers-soen341projectF2023/assets/118073058/806a5576-adbf-42e4-8a78-0dbcf21e7bff)
Clicking on a house post leads to the property page for which the mockup is 
![image](https://github.com/Broke-Brokers/Broke_BRokers-soen341projectF2023/assets/118073058/2d3e02b3-fc7e-4282-bb9e-77af938f5672)
The logos for this page have been updated on the github and google drive
![image](https://github.com/Broke-Brokers/Broke_BRokers-soen341projectF2023/assets/118073058/3caa5997-d74f-4d9c-ae38-c3a821dcdb76)
![image](https://github.com/Broke-Brokers/Broke_BRokers-soen341projectF2023/assets/118073058/57a367f1-0411-44e4-8e38-0f15206f6406)

**Comment by isaisa002** [comment]
@JPEUMZZ here's mockup for request visit page
![image](https://github.com/Broke-Brokers/Broke_BRokers-soen341projectF2023/assets/118073058/d83c63c4-5f3c-43ab-9e35-a8dbd7e4298b)

**Comment by isaisa002** [comment]
### User story: 

As a homeowner, renter or broker


- I want to be able consult a request visit page that allows me to show interest for a property
- When I get on the page, I want to see the main image of the house I want to do a request for 
- I want to see only the general information of the house (Price, post name, address & construction year)
- If I click on the main image of the house, I want to be directed to the property page of the house in a new tab
- I want to see information about the person responsible for the home visit so I can contact them if I want
- I want to submit the request by filling up a form where I can enter my name, email, phone
- I want to submit button to submit my form weither as a guest only, my account isn't associated with the form


As homeowner or renter
- I want a sign in button to submit my form and save it into my account

As a broker
- I want a sign in button to submit the form and save it into a client's file 


### Task Breakdown


- [ ] link back to search result
- [x] image of house exterior #60 #25 
- [ ] link property page to image of house exterior
- [x] Info : price #60 #25 
- [x] Adress #60 #25 
- [ ] Construction year #60 #25 
- [ ] Info of person responsible for house visit #RETRIEVE FROM DATABASE FOR REQUEST #25
- [ ] Your details section textview * editview
- [ ] [BUTTON] Submit: #POPULATE DATABSE FOR REQUEST #25 
- [ ] [BUTTON] Sign in: link to login page
- [ ] [BUTTON] Sign in: ON LOGIN PAGE  FOR HOMEOWNER/RENTER, after log in #POPULATE DATABSE FOR REQUEST #25  
- [ ] [BUTTON] Sign in: ON LOGIN PAGE  FOR BROOKER ....... ?mockup broker 
- [ ] BUTTON] Sign in: Pop up message (Your request was succesfully submit and saved)
