### ISSUE TITLE
51.1 Login Page Backbone

### ISSUE THREAD

**Issue by DominiqueProulx** [Broke-Brokers/Broke_BRokers-soen341projectF2023#68]
51.1 Login Page Backbone

- [x] Create backbone #54 
- [ ] Apply branding #50 
- [ ]  Verificator
- [ ]  fire up #25 

------

From Task #51
User Stories #9 #10 #11 #12

_Originally posted by @DominiqueProulx in https://github.com/Broke-Brokers/Broke_BRokers-soen341projectF2023/issues/51#issuecomment-1745718299_

**Comment by DominiqueProulx** [comment]
@taylcr You can merge the login page to the mai branch please ? here is the ID 
![image](https://github.com/Broke-Brokers/Broke_BRokers-soen341projectF2023/assets/129322102/f47fac1b-20ef-4274-828d-1e62f7ef3a36)

**Comment by taylcr** [comment]
FROM #51 
## TASK DESCRIPTION
As a developper, I want a page to allow user to login and sign in on the website
## ACCEPTANCE CRITERIA 

- [x] Field to enter username for log in
- [x] Field to enter password for Log in
- [x] Field to enter name for sign in
- [x] Field to enter email for sign in
- [x] Field to enter password for sign in
- [x] Allows user to ask for forgot password



![Image](https://github.com/Broke-Brokers/Broke_BRokers-soen341projectF2023/assets/31834057/4a49a39a-b742-4732-8357-92e9e9e6f842)



![Image](https://github.com/Broke-Brokers/Broke_BRokers-soen341projectF2023/assets/31834057/ebc3b02d-e75c-424f-ad11-3e85350fa09e)
