### ISSUE TITLE
Homebuyer and Renter contact forms

### ISSUE THREAD

**Issue by DominiqueProulx** [Broke-Brokers/Broke_BRokers-soen341projectF2023#72]
- [ ] contact form to brokers
- [ ] contact form to other homeowners?? 

we need to decide as a team how the contact will be handled -- through emails (contact forms ) or get a message through Our platform

**Comment by JPEUMZZ** [comment]
I will do it

**Comment by isaisa002** [comment]
@JPEUMZZ here's mockup for request visit page 
![image](https://github.com/Broke-Brokers/Broke_BRokers-soen341projectF2023/assets/118073058/ea9ecc58-d028-4704-99ad-b714b2590229)

**Comment by isaisa002** [comment]
> * [ ]  contact form to brokers
> * [ ]  contact form to other homeowners??
> 
> we need to decide as a team how the contact will be handled -- through emails (contact forms ) or get a message through Our platform

Will be decide in meeting 2023-10-21

**Comment by isaisa002** [comment]
## User story

### As a homeowner, renter or broker


- I want to be able consult a request visit page that allows me to show interest for a property
- When I get on the page, I want to see the main image of the house I want to do a request for 
- I want to see only the general information of the house (Price, post name, address & construction year)
- If I click on the main image of the house, I want to be directed to the property page of the house in a new tab
- I want to see information about the person responsible for the home visit so I can contact them if I want
- I want to submit the request by filling up a form where I can enter my name, email, phone
- I want to submit button to submit my form weither as a guest only, my account isn't associated with the form


### As homeowner or renter
- I want a sign in button to submit my form and save it into my account

### As a broker
- I want a sign in button to submit the form and save it into a client's file 


## Task Breakdown

- [ ] link back to search result
- [x] image of house exterior #60 #25 
- [x] link property page to image of house exterior
- [x] Info : price #60 #25 
- [x] Adress #60 #25 
- [x] Construction year #60 #25 
- [ ] Info of person responsible for house visit #RETRIEVE FROM DATABASE FOR REQUEST #25
- [x] Your details section textview * editview
- [ ] [BUTTON] Submit: #POPULATE DATABSE FOR REQUEST #25 
- [ ] [BUTTON] Sign in: link to login page
- [ ] [BUTTON] Sign in: ON LOGIN PAGE  FOR HOMEOWNER/RENTER, after log in #POPULATE DATABSE FOR REQUEST #25  
- [ ] [BUTTON] Sign in: ON LOGIN PAGE  FOR BROOKER ....... ?mockup broker 
- [ ] BUTTON] Sign in: Pop up message (Your request was succesfully submit and saved) 


## User acceptance flow 

1. On property page #97, user clicked on the request visit button #117 
2. User is leads to request visit page #72
3. User can go back to property page with the return back button or by clicking on the image of house exterior
4. User fill up request form
5. User submit as a guest with the submit button
6. User can submit and save into their account with the sign in button
7. If the user is already sign in, they are NOT redirected to the login page and the pop up message confirming the submission appears. 
8. If the user isn't already sign in, they are redirected to the login page
9. After entering their information and is succesfully sign in, the pop up message confirming the submission appears. 


## Acceptance criteria

- User acceptance flow in respected
- Documentation present for every new components
- Unit and Ul tests are implemented for every component and function 
- There must exist an automated Cypress acceptance test in GIF form
- Must match Mockup

**Comment by DominiqueProulx** [comment]
Form fields :

Name
Last Name
Phone Number
email
Prefered days  : click disc or box
prefered hour : scroll down or click disc or box with time blocks?

to be sent with the form : property_id integer PK

**Comment by DominiqueProulx** [comment]
TASK-1.3.1 Modify Request a visit form to accomodate  type of user

##Task description
- When I get on the page, I want to see the main image of the house I want to do a request for 
- I want to see only the general information of the house (Price, post name, address & construction year)
### As homeowner or renter
- I want a sign in button to submit my form and save it into my account

### As a broker
- I want a sign in button to submit the form and save it into a client's file 
### As homeowner or renter
- I want a sign in button to submit my form and save it into my account

### As a broker
- I want a sign in button to submit the form and save it into a client's file 


- If I click on the main image of the house, I want to be directed to the property page of the house in a new tab
- I want to see information about the person responsible for the home visit so I can contact them if I want

##Acceptance flow

6. User can submit and save into their account with the sign in button
7. If the user is already sign in, they are NOT redirected to the login page and the pop up message confirming the submission appears. 
8. If the user isn't already sign in, they are redirected to the login page

##task breakdown:
- [ ] link back to search result
- [ ] image of house exterior #60 #25 
- [ ] link property page to image of house exterior
- [ ] Info : price #60 #25 
- [ ] Adress #60 #25 
- [ ] Construction year #60 #25 
- [ ] Info of person responsible for house visit #RETRIEVE FROM DATABASE FOR REQUEST #25
- [ ] Your details section textview * editview
- [ ] [BUTTON] Submit: #POPULATE DATABSE FOR REQUEST #25 
- [ ] [BUTTON] Sign in: link to login page
- [ ] [BUTTON] Sign in: ON LOGIN PAGE  FOR HOMEOWNER/RENTER, after log in #POPULATE DATABSE FOR REQUEST #25  
- [ ] [BUTTON] Sign in: ON LOGIN PAGE  FOR BROOKER ....... ?mockup broker 
- [ ] BUTTON] Sign in: Pop up message (Your request was succesfully submit and saved)

**Comment by DominiqueProulx** [comment]
It was decided during meeting 21-10-2023 that it would be a pop up form , user story was modified to reflect these changes 
![image](https://github.com/Broke-Brokers/Broke_BRokers-soen341projectF2023/assets/129322102/fe98a5a0-6347-4710-8230-e773d8fba2ba)

**Comment by DominiqueProulx** [comment]
@JPEUMZZ  

![image](https://github.com/Broke-Brokers/Broke_BRokers-soen341projectF2023/assets/129322102/f5a437e2-6202-4a55-87a1-189d7f523020)


Arghh we forgot that one.  You think we can simply make a test for type of user and if it's broker you add a field "on behalf of client XX" when it sends the email  ???

**Comment by DominiqueProulx** [comment]
@BrokeBrokers 

I added the link to the form in two ways

## OPTION A  
Link directly to your request visit page

## OPTION B  
pop up.,


If you go on propertyPage  you can test the two buttons. 
The pop up would need styling if we decide to go this route. 
@JPEUMZZ I took your exact code and made a component out of it in /components/forms/ and put the component in the pop up using the [react popup ](https://www.npmjs.com/package/reactjs-popup)

I will delete the route or the component depending on what is chosen 

Let me know which way you would like to keep and i'll adjust.

**Comment by JPEUMZZ** [comment]
## After our meeting of 2023-11-05
It was decided to link the request visit button in property page to a request visit page.
In one section the page contains information about the property clicked and the broker associated and in the other section the form. Like this, other features such as make an offer, add to favorite, contact broker will have the same format

**Comment by JPEUMZZ** [comment]
For now

- [ ] The form send an email to the one entered

In sprint 4, the form could be enhanced so that 
- [ ] Prefered date & time is added 
- [ ] The email contains information entered by user
