### ISSUE TITLE
24.1 Property Search page

### ISSUE THREAD

**Issue by DominiqueProulx** [Broke-Brokers/Broke_BRokers-soen341projectF2023#89]
Creating Issue for Property search page

24.1 Property Search page 

- [ ] Property search from main navigaiton menu
- [ ] Property Search page:[SEARCH BAR]At the top.Bar with search criteria(location,city, neighborhood, ZIP code, price range, number of bedrooms, and amenities.) #60 
- [ ] Property Search page: [FILTER] At the top. List of common amenities or features that I can select or deselect to filter the properties.( options such as swimming pool, garage, garden, etc.) #60 
- [ ] Property Search page: [BUTTON] Request Visit
- [ ] Property Search page: [FORM](on request visit click) : open a form or dialog where I can provide the following information and submit them after:
* My preferred date and time for the viewing appointment.
* Contact information, including the name, email address, and phone number
- [ ] Property Search page: [FORM](on request form submit):  Confirmation message indicating that the request has been received by the system.
- [ ] Property Search page: [FORM](on request form submit):  Email confirmation to the email address provided, summarizing the details of the viewing request and receipt.
- [ ] Property Search page: [BUTTON] Button "save" when viewing a property.
- [ ]  Property Search page: (on save button click) : property saved to homebuyers Save list #49  #60

**Comment by DominiqueProulx** [comment]
duplicate

**Comment by DominiqueProulx** [comment]
duplicate of #96
