### ISSUE TITLE
1.4 User story 1 task breakdown for sprint #3

### ISSUE THREAD

**Issue by DominiqueProulx** [Broke-Brokers/Broke_BRokers-soen341projectF2023#91]
### FOR SPRINT 3

 **Search for Brokers**  IN SPRINT#3
- [x] Search for brokers profile : [SEARCHBAR]A search functionality where the user can enter criteria such as location, expertise, and customer reviews to find brokers. #63 
- [x] Search for brokers profile :  portfolio System displays a list of broker profiles that match the criteria. Broker profile should include information such as the broker's name, contact details, areas of expertise, customer reviews, and a photo. #72 
- [x] Search for brokers profile : (on click of broker's profile) : view detailed information such as their services.
- [x] Search for brokers profile :  [FORM] contact broker 

**Mortage calculator page** SPRINT 4

- [ ] Mortage calculator page : [FORM]The user can enter can loan amount, interest rate, loan term (in years), and property tax rate 
- [ ] Mortage calculator page : The calculator display the estimated monthly mortgage payment 

**For this task to be considered done these task must also be done : ** 
- [x] #68 must be done
- [x] #49 must be connected to login after #25 
- [x] #52  must be connected to brokers after #25 
- [x] #71 this page must be completed and working
- [x] #72 this page must be completed and working

_Originally posted by @DominiqueProulx in https://github.com/Broke-Brokers/Broke_BRokers-soen341projectF2023/issues/24#issuecomment-1753914563_
