### ISSUE TITLE
24.1 Property Search page 

### ISSUE THREAD

**Issue by DominiqueProulx** [Broke-Brokers/Broke_BRokers-soen341projectF2023#96]
Creating Issue for Property search page

24.1 Property Search page 

- [ ] Property search from main navigaiton menu
- [ ] Property Search page:[SEARCH BAR]At the top.Bar with search criteria(location,city, neighborhood, ZIP code, price range, number of bedrooms, and amenities.) #60 
- [ ] Property Search page: [FILTER] At the top. List of common amenities or features that I can select or deselect to filter the properties.( options such as swimming pool, garage, garden, etc.) #60 
- [ ] Property Search page: [BUTTON] Request Visit
- [ ] Property Search page: [FORM](on request visit click) : open a form or dialog where I can provide the following information and submit them after:
* My preferred date and time for the viewing appointment.
* Contact information, including the name, email address, and phone number
- [ ] Property Search page: [FORM](on request form submit):  Confirmation message indicating that the request has been received by the system.
- [ ] Property Search page: [FORM](on request form submit):  Email confirmation to the email address provided, summarizing the details of the viewing request and receipt.
- [ ] Property Search page: [BUTTON] Button "save" when viewing a property.
- [ ]  Property Search page: (on save button click) : property saved to homebuyers Save list #49  #60

_Originally posted by @DominiqueProulx in https://github.com/Broke-Brokers/Broke_BRokers-soen341projectF2023/issues/24#issuecomment-1751801635_

**Comment by DominiqueProulx** [comment]
Feature was merged.

Need to be done :
Search for City, Neighborhood
Remove delete button AFTER code was copied for https://github.com/Broke-Brokers/Broke_BRokers-soen341projectF2023/issues/181
Link from property to property page needs to be done

**Comment by DominiqueProulx** [comment]
created a branch to make the link to proeprty page : 

https://github.com/Broke-Brokers/Broke_BRokers-soen341projectF2023/tree/1.1.1_propertySearch--link-to-property_Dominique

**Comment by DominiqueProulx** [comment]
## Gallery house thumbnails link to property page
UNIT TEST
Expected :  on click of thumbnail, we are routed to property page
result : the link works.

unit test successful

**Comment by JPEUMZZ** [comment]
On the search page, a click on a house card leads to the property page but the property page doesn't contain information about the house card clicked. This could be enhanced in Sprint 4

**Comment by JPEUMZZ** [comment]
See #277 and  #278 for updates
Now in search property page, we can research a house based on specific criteria such as location, price range, number of bedrooms and bathrooms. The UI for the search bar could be enhanced. 
@DominiqueProulx added a unique key prop for each element
