### ISSUE TITLE
24.3 Property page

### ISSUE THREAD

**Issue by DominiqueProulx** [Broke-Brokers/Broke_BRokers-soen341projectF2023#97]
## User story :

As a homebuyer or a renter :

- I want to be able to consult a property page so that I can get all the details related to that property.
- when I get on that page I want to see the image that was used as thumbnail for the property in the search result so that I can recognized why I am on this page.
- I want to see a gallery of the images for this property so that I can see if it's interesting visually.
- I want to see information about the broker related to that property so that I can contact them if I am interested
- I want to see the price, the number of bathrooms, the number of rooms and a short description of the property
- I want to have a button to save the properties to my favorites so I can find it later in my favorite property page
- I want to have a button to request a visit to the property so that a broker contacts me to arrange a visit.

---

## Task breakdown

              24.3 Property page

### property page ### 

- [ ] link back to search result
- [x] image of house exterior#60 #25 
- [x] image of house interior#60 #25 
- [x] Info : price #60 #25 
- [x] Adress #60 #25 
- [ ] Construction year #60 #25 
- [x] rectangle with broker related to the house and contact info #34 #63 #25 
- [ ] [BUTTON] Request a visit #72
- [x] [BUTTON] Save to favorites #71 #25

_Originally posted by @DominiqueProulx in https://github.com/Broke-Brokers/Broke_BRokers-soen341projectF2023/issues/24#issuecomment-1756620176_

**Comment by DominiqueProulx** [comment]
![image](https://github.com/Broke-Brokers/Broke_BRokers-soen341projectF2023/assets/129322102/09410f9e-763e-47f8-b499-bf533b476e8c)

**Comment by DominiqueProulx** [comment]
link to the mockup : https://github.com/Broke-Brokers/Broke_BRokers-soen341projectF2023/issues/56

**Comment by DominiqueProulx** [comment]
I created a branch, added a gallery and a main picture

**Comment by DominiqueProulx** [comment]
![image](https://github.com/Broke-Brokers/Broke_BRokers-soen341projectF2023/assets/129322102/cc6228e5-c0a4-4332-8ba3-1fa47958c52b)

![image](https://github.com/Broke-Brokers/Broke_BRokers-soen341projectF2023/assets/129322102/0b056f07-c038-45ed-8fd6-861f0e38d8d1)

**Comment by DominiqueProulx** [comment]
- Gallery componenent imported
  - thumbnail moved to the right 
  -  play icon removed
  
- PropertyInfo box component created 
- Broker Card component created
----

I need to do : 

Button for save to favorite
Button for ask for visit 
create PropertyImage component 
add information to property info

**Comment by DominiqueProulx** [comment]
@RebeccaElusme  or @isaisa002 
I tried to follow the mockup , but the "image of interior" is smaller than the property profile picture, does  the way I did it look right to you ? 

for the save and ask for visit buttons :  @JPEUMZZ  I saw a button component, Is this the one I should be using or should I create a new one 


Thanks!

**Comment by JPEUMZZ** [comment]
@DominiqueProulx  You don't need to the components button that I created and you don't also have to create one react come with a default one <button> name_of_your_button </button>

**Comment by DominiqueProulx** [comment]
> @DominiqueProulx You don't need to the components button that I created and you don't also have to create one react come with a default one name_of_your_button

Got you, thanks

@JPEUMZZ  I  still create a component using this button and call it "SavePropertyToFavorite"  so we can re-use the component for the brokers , right?

**Comment by JPEUMZZ** [comment]
@DominiqueProulx  You can re-use a component many times as you want

**Comment by DominiqueProulx** [comment]
link to the property database field 

I will add the info of those field onto the page 
https://github.com/Broke-Brokers/Broke_BRokers-soen341projectF2023/issues/59

**Comment by isaisa002** [comment]
> @RebeccaElusme  or @isaisa002 
> 
> I tried to follow the mockup , but the "image of interior" is smaller than the property profile picture, does  the way I did it look right to you ? 
> 
> 
> 
> for the save and ask for visit buttons :  @JPEUMZZ  I saw a button component, Is this the one I should be using or should I create a new one 
> 
> 
> 
> 
> 
> Thanks!


Can the image and house description be in on frame and the brokers associated in another one ?

**Comment by DominiqueProulx** [comment]
> Can the image and house description be in on frame and the brokers associated in another one ?

For sure ! Would you like the same kind of container as the broker but with another color? 

idea : I can try to make the gallery fill width and bring the house image down.

**Comment by isaisa002** [comment]
> 
> 
> > Can the image and house description be in on frame and the brokers associated in another one ?
> 
> 
> 
> For sure ! Would you like the same kind of container as the broker but with another color? 
> 
> 
> 
> idea : I can try to make the gallery fill width and bring the house image down.

Sure !!!

**Comment by DominiqueProulx** [comment]
@isaisa002  what about this? 

![image](https://github.com/Broke-Brokers/Broke_BRokers-soen341projectF2023/assets/129322102/9ae94763-ce37-4378-a276-59915a90a974)
![image](https://github.com/Broke-Brokers/Broke_BRokers-soen341projectF2023/assets/129322102/5172d01a-cbe5-4142-8ec7-dc24c66529cb)
![image](https://github.com/Broke-Brokers/Broke_BRokers-soen341projectF2023/assets/129322102/7075884b-850b-4635-9d5b-f1a6c65e06bd)

**Comment by DominiqueProulx** [comment]
- modified the icons for the broker card component
- Added the fields to the property page as per the database fields
- Creation of the save to favorite button

![image](https://github.com/Broke-Brokers/Broke_BRokers-soen341projectF2023/assets/129322102/dcd8f5a0-95d9-488a-bac1-edb523f6119a)

**Comment by DominiqueProulx** [comment]
TASK-24.3.1 Request a visit button

##Task description 
As a homebuyer or renter, I need a button so that I can request a visit to the broker

##Acceptance Criteria

- [ ] button has the logo of mockup
- [ ] when clicked button opens brokers contact form
